build.gradle, src/main/java/UniFest/UniFestApplication.java, src/main/java/UniFest/auth/controller/AuthController.java, src/main/java/UniFest/auth/service/AuthService.java, src/main/java/UniFest/config/CacheConfig.java, src/main/java/UniFest/config/RedisConfig.java, src/main/java/UniFest/config/SecurityConfig.java, src/main/java/UniFest/domain/booth/controller/BoothController.java, src/main/java/UniFest/domain/booth/entity/Booth.java, src/main/java/UniFest/domain/booth/repository/BoothRepository.java, src/main/java/UniFest/domain/booth/service/BoothService.java, src/main/java/UniFest/domain/festival/controller/FestivalController.java, src/main/java/UniFest/domain/festival/service/FestivalService.java, src/main/java/UniFest/dto/request/booth/BoothCreateRequest.java, src/main/java/UniFest/dto/request/booth/BoothPatchRequest.java, src/main/java/UniFest/dto/response/booth/BoothDetailResponse.java, src/main/java/UniFest/exception/auth/NotAuthorizedException.java, src/main/java/UniFest/exception/booth/BoothNotFoundException.java, src/main/java/UniFest/exception/jwt/AccessTokenExpiredException.java, src/main/java/UniFest/exception/jwt/RefreshTokenExpiredException.java, src/main/java/UniFest/security/filter/JwtExceptionFilter.java, src/main/java/UniFest/security/filter/JwtVerificationFilter.java, src/main/java/UniFest/security/filter/LoginFilter.java, src/main/java/UniFest/security/jwt/JwtTokenizer.java, src/main/java/UniFest/security/redis/RedisRepository.java, src/main/resources/application.yml, src/test/java/UniFest/service/RedisCRUDTest.java, src/test/resources/application.yml
- redis를 이용한 캐싱 , 토큰재발급, 로그아웃 개발
- 레디스 설정
- 부스정보 수정 api 개발
- 부스 삭제 api개발
- 부스상세정보, 전체축제조회, 지역별축제조회 캐싱
- 수정 혹은 삭제시 캐싱된 데이터 삭제
- 리프레시토큰을 사용해 액세스토큰 재발급
- 로그아웃 - 레디스에서 리프레시 토큰 삭제
=> feat : redis를 이용한 캐싱 , 토큰재발급, 로그아웃 기능개발

src/main/java/UniFest/domain/festival/repository/FestivalRepository.java, src/main/java/UniFest/dto/response/festival/FestivalSearchResponse.java, src/main/java/UniFest/dto/response/festival/TodayFestivalInfo.java
- 안드로이드 측에서 필드 추가 요청
- 축제id와 학교id 필드 추가
- schoolId
- festivalId
- 
- 
-
=> Fix - 축제 조회 응답 Dto 필드 추가

src/main/java/UniFest/domain/star/service/EnrollService.java, src/main/java/UniFest/exception/OutOfPeriodException.java
- 요청의 연예인 방문 시기와 축제 기간이 맞지 않을 경우 예외 처리
- db connection - read-only
- EnrollService
- OutOfPeriodException
- Transactional 추가
- 
- 
-
=> Fix/enroll : 

src/main/java/UniFest/config/SecurityConfig.java, src/main/java/UniFest/dto/request/member/MemberSignUpRequest.java, src/main/java/UniFest/dto/response/booth/BoothResponse.java, src/main/java/UniFest/dto/response/member/MemberDetailResponse.java
- 회원가입/로그인 기능 수정
- Long에 NotBlank->NotNull
- MemberDetailResponse에 @Getter 추가
=> fix: 회원가입/로그인

src/main/java/UniFest/domain/star/controller/StarController.java, src/main/java/UniFest/dto/request/star/PostStarRequest.java
- 요청 Dto와 응답 Dto를 같이 사용하기 있었기에 이전의 수정으로 인해 요청에서도 Id를 받고 있음
- PostStarRequest Dto 추가 생성
- name, imageUrl
- 
- 
-
=> fix : Star 생성 요청 Dto 수정

src/main/java/UniFest/domain/menu/controller/MenuController.java, src/main/java/UniFest/domain/menu/service/MenuService.java, src/main/java/UniFest/exception/menu/MenuNotFoundException.java
- feat : 메뉴삭제 api 개발
- MenuNotFound 예외 작성
- 메뉴삭제 api 작성
- 
- 기존에 테스트용으로 있던 home controller, admin controller 삭제했습니다.
=> feat : 메뉴삭제 api 개발

src/main/java/UniFest/domain/star/controller/StarController.java, src/main/java/UniFest/domain/star/repository/StarRepository.java
- 축제에 연예인 등록 시 현재 db에 등록된 연예인의 id 알기 어려움
- StarController
- findAllStars
- StarRepository
- findAllStars
=> Feat/star : 등록된 연예인 전체 조회

src/main/java/UniFest/domain/booth/service/BoothService.java, src/main/java/UniFest/dto/request/booth/BoothPatchRequest.java
> ### 개요
> fix : BoothPatchRequest enabled,위경도 참조타입으로 변경
> 
> ### 작업사항
> boolean -> Boolean
> double -> Double
> 
> ### 주의사항
=> fix : BoothPatchRequest enabled,위경도 참조타입으로 변경

src/main/java/UniFest/domain/booth/service/BoothService.java, src/main/java/UniFest/domain/menu/controller/MenuController.java, src/main/java/UniFest/domain/menu/service/MenuService.java, src/main/java/UniFest/dto/request/booth/BoothCreateRequest.java
> ### 개요
> fix : 부스생성시 메뉴생성dto 포함해서 생성할 수 있도록 로직변경
> 
> ### 작업사항
> 기존에 있던 부스에 메뉴를 추가하는게 아닌 부스 생성시 메뉴생성도 함께 할 수 있도록 수정
> BoothCreateRequest
> ### 주의사항
=> fix : 부스생성시 메뉴생성dto 포함해서 생성할 수 있도록 로직변경

src/main/java/UniFest/domain/booth/entity/Booth.java, src/main/java/UniFest/domain/booth/service/BoothService.java, src/main/java/UniFest/domain/menu/controller/MenuController.java, src/main/java/UniFest/domain/menu/entity/Menu.java, src/main/java/UniFest/domain/menu/service/MenuService.java, src/main/java/UniFest/domain/waiting/controller/WaitingController.java, src/main/java/UniFest/dto/request/menu/MenuStatusChangeRequest.java
- 부스 웨이팅 지원 여부
- 메뉴의 재고 상태
기능 추가하여 풀리퀘합니다
=> feat : booth waiting enabled / menu status

src/main/java/UniFest/domain/booth/service/BoothService.java
- boothService
> - CacheEvict 적용 안되어 있던 것을 수정
=> fix: boothService adapt cache logic

src/main/java/UniFest/dto/request/PostEnrollRequest.java, src/main/java/UniFest/dto/request/festival/PostFestivalRequest.java, src/main/java/UniFest/dto/response/festival/FestivalSearchResponse.java, src/main/java/UniFest/dto/response/festival/TodayFestivalInfo.java
LocalDate에 JsonFormat 어노테이션 적용
=> fix: applying format to LocalDate

src/main/java/UniFest/domain/booth/service/BoothService.java, src/main/java/UniFest/domain/waiting/controller/WaitingController.java, src/main/java/UniFest/domain/waiting/entity/Waiting.java, src/main/java/UniFest/domain/waiting/repository/WaitingRepository.java, src/main/java/UniFest/domain/waiting/service/WaitingService.java, src/main/java/UniFest/dto/response/waiting/WaitingInfo.java, src/main/java/UniFest/exception/booth/PinNotCreatedException.java
Reverts Project-Unifest/unifest-server#80
=> Revert "fix: get pin 시도시 핀 존재하지 않으면 에러, 부스 생성시 pin 생성"

src/main/java/UniFest/dto/response/waiting/WaitingInfo.java
=> fix: apply format

src/main/java/UniFest/domain/waiting/controller/WaitingController.java, src/main/java/UniFest/domain/waiting/repository/WaitingRepository.java, src/main/java/UniFest/domain/waiting/service/WaitingService.java, src/main/java/UniFest/dto/request/waiting/CheckPinRequest.java, src/main/java/UniFest/dto/request/waiting/DeleteWaitingRequest.java, src/main/java/UniFest/dto/request/waiting/PostWaitingRequest.java, src/main/java/UniFest/dto/response/waiting/WaitingInfo.java
Reverts Project-Unifest/unifest-server#84
=> Revert "merge: dev to main"

src/main/java/UniFest/domain/booth/service/BoothService.java, src/main/java/UniFest/dto/request/booth/BoothCreateRequest.java
=> fix: make opening/closing time nullable

src/main/java/UniFest/domain/menu/controller/MenuController.java, src/main/java/UniFest/domain/menu/service/MenuService.java, src/main/java/UniFest/dto/request/menu/MenuStatusChangeRequest.java
잘못 작성된 부분이 있어 수정합니다
- pathVariable 누락
- Request DTO 수정
=> fix: status 변경부분 수정

src/main/java/UniFest/config/SecurityConfig.java, src/main/java/UniFest/domain/member/controller/MemberController.java
This reverts commit 70d5038b9fd6db4b501b16e2837f482e9e321ac9.
=> Revert "fix: 본인 탈퇴 기능 막음"

src/main/java/UniFest/domain/waiting/service/WaitingService.java
=> fix: drop completed 'waiting' from my waiting

src/main/java/UniFest/domain/booth/entity/Booth.java, src/main/java/UniFest/dto/request/booth/BoothCreateRequest.java
This reverts commit bb835f913dd03867ade731caf0c7247a01207680.
=> Revert "hotfix: 부스 이름 길이제한 수정"

src/main/java/UniFest/domain/booth/controller/BoothController.java, src/main/java/UniFest/domain/booth/entity/Booth.java, src/main/java/UniFest/domain/booth/entity/BoothSchedule.java, src/main/java/UniFest/domain/booth/service/BoothService.java, src/main/java/UniFest/domain/booth/utils/BoothEnabledScheduler.java, src/main/java/UniFest/dto/request/booth/BoothCreateRequest.java, src/main/java/UniFest/dto/request/booth/BoothPatchRequest.java, src/main/java/UniFest/dto/request/booth/BoothScheduleAddRequest.java, src/main/java/UniFest/dto/request/booth/BoothScheduleCreateRequest.java, src/main/java/UniFest/dto/request/booth/BoothSchedulePatchRequest.java, src/main/java/UniFest/dto/response/booth/BoothDetailResponse.java, src/main/java/UniFest/dto/response/booth/BoothScheduleResponse.java
Reverts Project-Unifest/unifest-server#154
죄송합니다...
=> Revert "Revert "feat:BoothSchedule 추가""

src/main/java/UniFest/domain/festival/controller/InterestController.java, src/main/java/UniFest/domain/festival/repository/InterestRepository.java, src/main/java/UniFest/domain/festival/service/InterestService.java, src/main/java/UniFest/dto/request/festival/InterestRequest.java
- Implemented retrieval of festival IDs registered as interests based on deviceId
- Used InterestRepository to fetch interests associated with a given deviceId
- Converted the result into a list of festival IDs using stream mapping
=> feat: add interest festival list retrieval feature

src/main/java/UniFest/domain/admin/AdminController.java, src/main/java/UniFest/domain/booth/controller/BoothController.java, src/main/java/UniFest/domain/festival/controller/FestivalController.java, src/main/java/UniFest/domain/festival/controller/InterestController.java, src/main/java/UniFest/domain/megaphone/controller/MegaphoneController.java, src/main/java/UniFest/domain/member/controller/MemberController.java, src/main/java/UniFest/domain/menu/controller/MenuController.java, src/main/java/UniFest/domain/star/controller/StarController.java, src/main/java/UniFest/global/common/exception/ExceptionController.java, src/main/java/UniFest/global/common/exception/UnifestCustomException.java, src/main/java/UniFest/global/common/response/ErrorResponse.java, src/main/java/UniFest/global/common/response/Response.java
- Changed Response<Long> to Response<Void> where applicable
- Removed unnecessary null values in Response.ofSuccess() returns
- Improved consistency across controllers
=> refactor(api): update Response type in multiple controllers

src/main/java/UniFest/domain/booth/dto/request/BoothCreateRequest.java, src/main/java/UniFest/domain/booth/dto/response/BoothResponse.java, src/main/java/UniFest/domain/booth/service/BoothService.java
Boothschedules -> scheduleList
=> fix: property명 통일

src/main/java/UniFest/domain/stamp/controller/StampController.java, src/main/java/UniFest/domain/stamp/dto/response/StampEnabledFestivalResponse.java
Reverts Project-Unifest/unifest-server#190
=> Revert "Revert "fix: 누락된 파일 commit""

src/main/java/UniFest/domain/festival/dto/request/PostFestivalRequest.java, src/main/java/UniFest/domain/menu/dto/request/MenuPatchRequest.java, src/main/java/UniFest/domain/stamp/dto/request/StampEnabledRequest.java, src/main/java/UniFest/domain/stamp/dto/request/StampInfoCreateRequest.java, src/main/java/UniFest/domain/stamp/dto/request/StampInfoUpdateRequest.java, src/main/java/UniFest/domain/stamp/dto/request/StampRequest.java
@Schema(name ~) -> @Schema(description ~)
=> fix: 오타 수정

src/main/java/UniFest/domain/stamp/dto/response/StampEnabledFestivalResponse.java, src/main/java/UniFest/domain/stamp/service/StampService.java
=> feat: 드롭다운용 API에 property 추가

src/main/java/UniFest/global/infra/fileupload/controller/FileController.java
FileController에서
ResponseEntity<FileResponse> -> Response<FileResponse>
=> fix: response 전달방식 통일 (FileResponse)

src/main/java/UniFest/domain/booth/exception/BoothNotFoundException.java, src/main/java/UniFest/domain/booth/exception/OpeningTimeNotCorrectException.java, src/main/java/UniFest/domain/booth/exception/PinNotCreatedException.java, src/main/java/UniFest/domain/member/exception/MemberEmailExistException.java, src/main/java/UniFest/domain/member/exception/MemberNotFoundException.java, src/main/java/UniFest/domain/menu/exception/MenuNotFoundException.java, src/main/java/UniFest/domain/school/exception/SchoolNotFoundException.java, src/main/java/UniFest/domain/star/exception/OutOfPeriodException.java, src/main/java/UniFest/domain/star/exception/StarNotFoundException.java, src/main/java/UniFest/global/infra/auth/exception/NotAuthorizedException.java, src/main/java/UniFest/global/infra/fcm/exception/FcmFailException.java, src/main/java/UniFest/global/infra/fileupload/exception/ImageConvertingFailedException.java, src/main/java/UniFest/global/infra/fileupload/exception/UploadSizeExceedException.java, src/main/java/UniFest/global/infra/security/jwt/exception/AccessTokenExpiredException.java, src/main/java/UniFest/global/infra/security/jwt/exception/TokenNotValidateException.java
- Infra : 1000 번대
- Security : 2000 번대
- Booth : 3000 번대
- Festival : 4000 번대
- Member : 5000 번대
- Menu : 6000 번대
- School : 7000 번대
- Star : 8000 번대
- Stamp : 9000 번대
=> fix: Custom Error Code 정리

src/main/java/UniFest/domain/stamp/entity/StampRecord.java, src/main/java/UniFest/domain/stamp/service/StampService.java
- StampRecord 생성자 수정
- StampService 생성자 수정에 따른 Logic 수정
=> fix: 누락 코드 수정

src/main/java/UniFest/domain/festival/controller/FestivalController.java, src/main/java/UniFest/domain/festival/dto/request/FestivalModifyRequest.java, src/main/java/UniFest/domain/festival/entity/Festival.java, src/main/java/UniFest/domain/festival/service/FestivalService.java
- Festival : 일부 필드 setter 추가
- FestivalController : EndPoint 추가
- FestivalModifyRequest 추가
- FestivalService : Logic
=> feat: Festival 수정하는 endPoint 추가

src/main/resources/application.yml
=> chore: dll 변경

src/main/java/UniFest/domain/festival/dto/request/PostFestivalRequest.java
-PostFestivalRequest Annotation 변경 (기존(삭제) -> @Data)
=> hotfix: DTO 수정

src/main/java/UniFest/global/infra/fcm/FcmUtils.java
- apns-priority 헤더를 10으로 설정해 iOS 즉시 알림 보장
- AndroidNotification에 제목, 내용, 기본 진동 및 소리 설정 포함
- Notification 객체 대신 플랫폼별 알림 설정으로 중복 충돌로 인한 ios 소리 안나는 문제 방지 및 안정성 향상
- 메타데이터 추가 로직 유지 및 예외 처리 개선
=> feat(fcm): iOS 및 Android 알림 소리와 진동 설정 개선

src/main/java/UniFest/domain/booth/service/BoothService.java
=> fix: 상위 5개 Booth 조회시, 없는 Festival이면 예외처리

src/main/java/UniFest/global/infra/fcm/config/FcmConfig.java
Reverts Project-Unifest/unifest-server#259
=> Revert "hotfix : FcmConfig 수정"

src/main/java/UniFest/global/infra/fcm/config/FcmConfig.java
- 기존 방식처럼 환경변수에 직접 firebase.json 내용을 담는 것이 불안정
- 이를 파일로 빼내는 작업을 진행했습니다
- 앞으로 환경변수 FIREBASE_KEY에는 해당 json 파일의 주소를 담아주시기 바랍니다
=> 기존방식처럼 환경변수에 직접 firebase json 내용을 담는 것이 불안정하여 이를 파일로 빼내는 작업을 진행했습니다

build.gradle, src/main/resources/application-prod.yml
운영 환경에서만 sentry 가 동작하도록 했습니다
환경 변수만 추가해두면 될 것 같아요
메일 알려주시면 sentry 초대해드리겠습니다
=> chore: add sentry(for production only)

build.gradle
=> fix: sentry 버전 수정

Makefile
=> fix: 수동배포 스크립트 환경변수 수정
